spring:
  application:
    name: ms-card
  jpa:
    database: POSTGRESQL
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  main:
    allow-bean-definition-overriding: true

application:
  security:
    authentication:
      jwt:
        secret: hojjrbj6ln5mdnzeh9fikrfbamcy33puuwh3f8190jmf9vbv0ek2vym6tf74zjg0npj7d31xm6mzz7e6sv8bpvmjdcjoc2z0k8uzk02j03jfjl5scsgivh3p5yt9sa6k
        token-validity-in-seconds: 900
        time-to-live-in-cache: 900

server:
  servlet:
    session:
      cookie:
        http-only: true